<?php 

$actividades[]=array(
		array("ImgPonente"=>"<img src='img/Nacho_Alvarez.jpg' alt=''>",
			"NamePonente"=>"José Ignacio Álvarez Ruiz",
			"InfoPon"=>"Research&Devel engineer at @Redsys_es Software Engineer with experience in #Linux, #Python, #Android, #PHP, #J2EE and #FLOSS enthusiastic. https://goo.gl/LMSCi9",
			"NameActivity"=>"Sistemas de control de versiones distribuidas - Controla las versiones de tu trabajo con GIT",
			"Info"=>"Se mostrarán los comandos de git sobre repositorios de ejemplo reales de forma interactiva. También se darán sus alternativas sobre interfaz gráfica y se comentarán las estrategias de merge más efectivas.",
			"Dia"=>"Lunes",
			"Hora"=>"8:30 - 9:45",
			"Empresa"=>"Redsys"),
		array("ImgPonente"=>"<img src='img/Nacho_Alvarez.jpg' alt=''>",
			"NamePonente"=>"José Ignacio Álvarez Ruiz",
			"InfoPon"=>"Research&Devel engineer at @Redsys_es Software Engineer with experience in #Linux, #Python, #Android, #PHP, #J2EE and #FLOSS enthusiastic. https://goo.gl/LMSCi9",
			"NameActivity"=>"Servicios web con Python + web.py (Homenaje a Aaron Swartz)",
			"Info"=>"Se repasará la descripción de servicios Web y tecnologías SOAP/REST. A continuación, se presenta el microframework web.py desarrollado por Aaron Swartz para la generación y despliegue de servicios Web.",
			"Dia"=>"Lunes",
			"Hora"=>"9:45 - 10:45",
			"Empresa"=>"Redsys"),
		array("ImgPonente"=>"<img src='img/FcoJavier_Carazo.jpeg' alt=''>",
			"NamePonente"=>" Fco. Javier Carazo Gil",
			"InfoPon"=>"Research&Devel engineer at @Redsys_es Software Engineer with experience in #Linux, #Python, #Android, #PHP, #J2EE and #FLOSS enthusiastic. https://goo.gl/LMSCi9",
			"NameActivity"=>"WooCommerce: crea tu propia tienda online",
			"Info"=>"WooCommerce es el estándar de facto para crear tiendas online a día de hoy. Sus ventajas son muchas, pero hay dos que destacan, la primera de ellas es que usa WordPress (el CMS que da servicio a más del 25% de todo Internet). La segunda es que es realmente fácil de instalar, de mantener y de administrar (y por supuesto de comprar con él). El ecommerce es algo que llama mucho la atención no sólo por la parte tecnológica, sino porque es una tecnología que fomenta como pocas el auto empleo y el empleo por cuenta ajena. Los hábitos de compra a día de hoy tiran en esa dirección así que seguro que será una actividad que despierte curiosidad y sea un buen comienzo en una serie de tecnologías que tienen mucha empleabilidad y fomentan el emprendimiento.",
			"Dia"=>"Lunes",
			"Hora"=>"11:45 - 12:15",
			"Empresa"=>"Codection"),
		array("ImgPonente"=>"<img src='img/Rafael_Delgado.jpg' alt=''>",
			"NamePonente"=>"Rafael Delgado",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"Envenenamiento DNS",
			"Info"=>"Es una situación creada de manera maliciosa que provee datos manipulados de un servidor DNS falso, con el objetivo de robar información al usuario. Realizaré una prueba de ataque real en directo y explicaré cómo funciona esta vulnerabilidad. Posteriormente, explicaré cómo evitar estos ataques y la cantidad de usuarios que hoy día siguen usando Windows XP.",
			"Dia"=>"Lunes",
			"Hora"=>"12:20 - 13:20",
			"Empresa"=>"ASIR"),
		array("ImgPonente"=>"<img src='img/RafaMellado_DanielGestino.jpg' alt=''>",
			"NamePonente"=>"Rafa y Dani",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"Introducción Angular 5 y Angular Material",
			"Info"=>"Realizaremos un taller de iniciación en Angular 5 y Angular Material en el que explicaremos las características más importantes de angular para los principiantes y haremos un taller guiado con una búsqueda “en caliente” de diferentes elementos, añadiendo y eliminando dichos elementos.",
			"Dia"=>"Lunes",
			"Hora"=>"12:20 - 13:20",
			"Empresa"=>"DAW"),
		array("ImgPonente"=>"<img src='img/NievesBorrero_PabloLeon.jpg' alt=''>",
			"NamePonente"=>"Pablo y Nieves",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"Tweepy. Cuando Python escucha lo que dice un pajarito",
			"Info"=>"Una charla sobre las posibilidades que nos ofrece Tweepy, una librería de Python que nos permite trabajar de forma sencilla con la API de twitter.",
			"Dia"=>"Lunes",
			"Hora"=>"13:30 - 14:15",
			"Empresa"=>"DAW"),

		/*MARTES*/

		array("ImgPonente"=>"<img src='img/Edu_Sanchez.jpg' alt=''>",
			"NamePonente"=>"Eduardo Sánchez Toril",
			"InfoPon"=>"Ing.Informático - Profesor de FP - Máster en Seguridad TIC - Fundador de Security High School.Cofundador de @HackandBeers @QurtubaCon y @ANPhacket.",
			"NameActivity"=>"Geolocalización de usuarios sin GPS",
			"Info"=>"Cómo pueden geolozalizar usuarios sin GPS y herramientas de uso",
			"Dia"=>"Martes",
			"Hora"=>"9:00 - 10:00",
			"Empresa"=>"IES Fidiana"),
		array("ImgPonente"=>"<img src='img/MiguelAngel_Arroyo.jpg' alt=''>",
			"NamePonente"=>"Miguel Ángel Arroyo",
			"InfoPon"=>"Auditor de seguridad de sistemas de información CEH por EC-Council. Formador en cursos de seguridad de la información. Autor del blog hacking-etico.com. Propulsor de la comunidad Hack&Beers. Colaborador del periódico digital cordopolis.es. Especialidades: Auditorías de Seguridad, Pruebas de Intrusión, Hacking Ético y Formación.",
			"NameActivity"=>"Introducción al análisis de binarios",
			"Info"=>"El objetivo de la charla es el de introducir a los asistentes en el análisis de binarios, uno de las áreas más complejas y potentes del cambo de la seguridad informática, indicando en qué campos de la seguridad es útil este conocimiento y se hará una demostración práctica con el análisis de varios binarios.",
			"Dia"=>"Martes",
			"Hora"=>"10:00 - 11:30",
			"Empresa"=>"SVTCloud"),
		array("ImgPonente"=>"<img src='img/dobuss.jpeg' alt=''>",
			"NamePonente"=>"JL García-Morato y José Huertas",
			"InfoPon"=>"Diseño web y posicionamiento web en Córdoba. #web #tiendaonline #MarketingDigital #Posicionamiento #SEO #RedesSociales #DiseñoWeb #ImagenCorporativa",
			"NameActivity"=>"Digital MKG: herramientas para analizar webs - @dobussmkt",
			"Info"=>"Repaso de herramientas usadas en el Marketing Digital para analizar webs",
			"Dia"=>"Martes",
			"Hora"=>"12:00 - 13:00",
			"Empresa"=>"Dobuss"),
		array("ImgPonente"=>"<img src='img/Nicolas_Garcia.jpg' alt=''>",
			"NamePonente"=>"Nicolás García Pedrajas",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"Deep-Learning",
			"Info"=>"Aprendizaje automático basados en asimilar representaciones de datos. En este paradigma los algoritmos son capaces de aprender sin intervención humana previa, sacando ellos mismos las conclusiones acerca de la semántica embebida en los datos.",
			"Dia"=>"Martes",
			"Hora"=>"13:00 - 14:30",
			"Empresa"=>"UCO"),

		/*Miercoles*/

		array("ImgPonente"=>"<img src='img/Claudia_Lopez.jpg' alt=''>",
			"NamePonente"=>"Claudia López Iglesias",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>'Design IS + workshop "Diseño con Illustrator"',
			"Info"=>"Breves conceptos de diseño sobre color, fundamentos de diseño, composición, tipografía y tendencias 2018. Iniciación a Illustrator CC (nivel básico) : herramientas, espacios de trabajo, documentos (exportar y tipos), gestión del color, tipografías…",
			"Dia"=>"Miércoles",
			"Hora"=>"8:30 - 10:30",
			"Empresa"=>"WUL4"),
		array("ImgPonente"=>"<img src='img/grayhtats.png' alt=''>",
			"NamePonente"=>"Javier Jiménez",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"Cloud computing y AWS",
			"Info"=>"Charla sobre cloud computing, amazon web services y salidas profesionales",
			"Dia"=>"Miércoles",
			"Hora"=>"8:30 - 9:00",
			"Empresa"=>"Gray Htats"),
		array("ImgPonente"=>"<img src='img/Rafa_Sojo.jpg' alt=''>",
			"NamePonente"=>"Rafa Sojo",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"CTF",
			"Info"=>"Nuestros alumnos competirán en grupos en un CTF organizado por Rafa Sojo. ¿Quién Ganará?",
			"Dia"=>"Miércoles",
			"Hora"=>"9:00 - 11:00",
			"Empresa"=>"1º DAW"),
		array("ImgPonente"=>"<img src='img/Rafa_Sojo.jpg' alt=''>",
			"NamePonente"=>"Rafa Sojo",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"Web scraping like a ninja",
			"Info"=>"Qué es web scraping y técnicas y herramientas de uso",
			"Dia"=>"Miércoles",
			"Hora"=>"11:00 - 11:30",
			"Empresa"=>"1º DAW"),
		array("ImgPonente"=>"<img src='img/Lazona.png' alt=''>",
			"NamePonente"=>"Rafael Rodríguez ",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"Coworking",
			"Info"=>"En un sector en constante evolución y con necesidades cada vez más interdisciplinares como es el tecnológico, trabajar conectado a una comunidad de profesionales tanto de tu propio área como de áreas colaterales es cada vez más importante. Los espacios de trabajo colaborativo o coworkings son una alternativa que permite a trabajadores autónomos y pequeñas empresas compartir en su día a día ideas, proyectos, contactos… a la vez que reducen y flexibilizan los costes fijos que supone mantener una oficina propia.",
			"Dia"=>"Miércoles",
			"Hora"=>"12:00 - 12:30",
			"Empresa"=>"La Zona"),
		array("ImgPonente"=>"<img src='img/Javier_Aguirre.jpg' alt=''>",
			"NamePonente"=>"Javier Aguirre",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"ChatBots",
			"Info"=>"Chatbots! Todo el mundo habla de ellos, pero qué son y por dónde empezar? Veremos de dónde vienen los chatbots y cómo empezar a implementar uno",
			"Dia"=>"Miércoles",
			"Hora"=>"12:30 - 13:30",
			"Empresa"=>"Reply.ai"),
		array("ImgPonente"=>"<img src='img/Cristina_Santamaria.jpg' alt=''>",
			"NamePonente"=>" Cristina Santamaria",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"Taller sobre Bots 102",
			"Info"=>"Aprenderemos a diseñar un chatbot con Chatfuel y Dialogflow",
			"Dia"=>"Miércoles",
			"Hora"=>"13:30 - 14:30",
			"Empresa"=>"The Neon Project"),

		/*Jueves*/

		array("ImgPonente"=>"<img src='img/Raul_Valentin.jpg' alt=''>",
			"NamePonente"=>"Raúl Valentín",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"Cómo construir un modelo predictivo con Machine Learning",
			"Info"=>"Entre todos construiremos un modelo predictivo. Un grupo de alumnos será nuestro conjunto de datos de entrenamiento con los que entrenaremos el modelo. Una vez construido el modelo otro grupo de alumnos lo testeará y determinaremos su rendimiento. Finalmente veremos un modelo real aplicado en San Juan de Dios para predecir el absentismo a consulta",
			"Dia"=>"Jueves",
			"Hora"=>"8:30 - 9:20",
			"Empresa"=>"Hospital San Juan de Dios"),
		array("ImgPonente"=>"<img src='img/Manuel_Jiménez.jpg' alt=''>",
			"NamePonente"=>"Manuel Jiménez",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"Producción de Realidad Virtual",
			"Info"=>"Taller introductorio al uso de CoSpaces, una herramienta web que permite de forma sencilla y directa producir escenas inmersivas e interactivas, usar modelos 3D predefinidos o incorporar los propios y pudiendo programar los eventos con un lenguaje de bloques o directamente con código.",
			"Dia"=>"Jueves",
			"Hora"=>"9:20 - 11:20",
			"Empresa"=>"CEP Córdoba"),
		array("ImgPonente"=>"<img src='img/Innovation_Group.png' alt=''>",
			"NamePonente"=>"Rafael Gómez",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"Cloud y contenerización con Docker",
			"Info"=>"Charla sobre Cloud, Docker, Puppet y Devops",
			"Dia"=>"Jueves",
			"Hora"=>"12:00 - 13:00",
			"Empresa"=>"Innovation Group"),
		array("ImgPonente"=>"<img src='img/Cristina_Triviño_Pepe_Molinero.jpg' alt=''>",
			"NamePonente"=>"Cristina Triviño y  Pepe Molinero",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"Crea tu propia nube",
			"Info"=>"Implementación y explicación de servicio Web y de Nextcloud en una raspberry pi 3",
			"Dia"=>"Jueves",
			"Hora"=>"13:00 - 14:00",
			"Empresa"=>"2º ASIR"),
		array("ImgPonente"=>"<img src='img/Innovation_Group.png' alt=''>",
			"NamePonente"=>"Alvaro Mesa , Raul Zarza y Antonio Arteche",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"Testing en el marco de trabajo Scrum",
			"Info"=>"Charla sobre las fases de vida de desarrollo software en el marco de Scrum y las actividades que un tester lleva a cabo en cada una de ellas para asegurar la calidad del software",
			"Dia"=>"Jueves",
			"Hora"=>"13:00 - 14:00",
			"Empresa"=>"Innovation Group"),

		/*Viernes*/

		array("ImgPonente"=>"<img src='img/LlamasFran_FernandezDavid.jpg' alt=''>",
			"NamePonente"=>"David Fernández Gómez, Antonio David Ventura Serrano y Francisco Llamas Nuflo",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"Criptomonedas y altcoin",
			"Info"=>"Introducción al mundo de las criptomonedas. Herramientas, utilidades, monederos, minería.",
			"Dia"=>"Viernes",
			"Hora"=>"8:15 - 9:15",
			"Empresa"=>"1º ASIR"),
		array("ImgPonente"=>"<img src='img/JuanAntonio_Romero.jpg' alt=''>",
			"NamePonente"=>"Juan Antonio Romero",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"Iniciación al desarrollo de servicios REST",
			"Info"=>"Introducción al desarrollo de una REST API. Veremos los motivos para desarrollar aplicaciones con esta arquitectura y la teoría para llevarlo a cabo, tratando de seguir las buenas prácticas. Después se mostrará un ejemplo básico desarrollado con Django. Se ha habilitado la compatibilidad con el lector de pantalla.",
			"Dia"=>"Viernes",
			"Hora"=>"8:15 - 9:15",
			"Empresa"=>"Sopinet"),
		array("ImgPonente"=>"<img src='img/Fernando_Hidalgo.jpg' alt=''>",
			"NamePonente"=>"Fernando Hidalgo",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"Más allá de Agile",
			"Info"=>"Cómo se estructura Sopinet Software y cómo se implementa nuestra ambiciosa filosofía, basada en tres pilares Agile: Transparencia, Sin miedo y Valor humano. Cómo luchamos continuamente contra la corriente de lo tradicional yendo #masalladeagile. En ella, hablaré, entre otras cosas, de:- Nuestra política salarial, transparente y establecida a través de fórmulas- Nuestra transparencia y métricas implementada con nuestras bombillas inteligentes- etc….",
			"Dia"=>"Viernes",
			"Hora"=>"9:15 - 10:00",
			"Empresa"=>"Sopinet"),
		array("ImgPonente"=>"<img src='img/Brecha_digital.jpg' alt=''>",
			"NamePonente"=>"Ana María Cuenca, María Moreno, Nieves Borrero y Soledad Cruz",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"¿Igualdad de género en el mundo tecnológico? Brecha digital",
			"Info"=>"¿Existe la desigualdad de género en el mundo tecnológico o, por el contrario, la tecnología reduce la desigualdad entre hombres y mujeres?",
			"Dia"=>"Viernes",
			"Hora"=>"10:00 - 10:45",
			"Empresa"=>"IES Gran Capitán"),
		array("ImgPonente"=>"<img src='img/cartelSysmana.jpg' alt=''>",
			"NamePonente"=>"Profesorado",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"II Concurso Twitter Sysmana. Entrega de premios",
			"Info"=>"Entrega de premios del II Concurso Twitter Sysmana 2018",
			"Dia"=>"Viernes",
			"Hora"=>"10:45 - 11:15",
			"Empresa"=>"IES Gran Capitán"),
		array("ImgPonente"=>"<img src='img/junta.jpg' alt=''>",
			"NamePonente"=>"Antonio López",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"Clausura (Delegado Educación)",
			"Info"=>"Clausura de la Sysmana por el Delegado de Educación Antonio López",
			"Dia"=>"Viernes",
			"Hora"=>"11:45 - 12:15",
			"Empresa"=>"Junta de Andalucía"),
		array("ImgPonente"=>"<img src='img/Álvaro_Serrano.jpg' alt=''>",
			"NamePonente"=>"Álvaro Serrano",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"Realidad Aumentada con WebGL",
			"Info"=>"En el taller de WebGL de este año crearemos una sencilla aplicación de Realidad Aumentada utilizando tecnologías web, gracias a frameworks de código abierto como A-Frame y AR.js",
			"Dia"=>"Viernes",
			"Hora"=>"12:15 - 14:15",
			"Empresa"=>"TangramBMP"),
		array("ImgPonente"=>"<img src='img/Lucia_Expósito.jpg' alt=''>",
			"NamePonente"=>"Lucia Expósito",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"¿Soy vulnerable?",
			"Info"=>"Charla sobre la vulnerabilidad móvil a través de bluetooth por blueborn",
			"Dia"=>"Viernes",
			"Hora"=>"12:15 - 12:45",
			"Empresa"=>"SVTCloud"),
		array("ImgPonente"=>"<img src='img/Manuel_Hidalgo.png' alt=''>",
			"NamePonente"=>"Manuel Hidalgo",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"Horus is coming... o casi",
			"Info"=>"Uso de nuevas tecnologías (elk, programas open source y scripting) para monitorizar en tiempo real equipos y sus servicios.",
			"Dia"=>"Viernes",
			"Hora"=>"12:45 - 14:15",
			"Empresa"=>"SVTCloud"),
		array("ImgPonente"=>"<img src='img/VueVSReact.png' alt=''>",
			"NamePonente"=>"Javier Ponferrrada, Jesús Mejías, Juan Rueda y Miguel Ángel Gavilán",
			"InfoPon"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam tenetur quos quibusdam ut nihil praesentium itaque, fugiat quod dolores nam soluta veniam impedit enim aperiam harum numquam eaque amet distinctio.",
			"NameActivity"=>"Vue vs React",
			"Info"=>"Taller de iniciación de Vue y React, donde se explicarán las características más importantes y las diferencias entre ellos, además de realizar ejemplos prácticos y guiados de cada uno de ellos para aprender a usar ambos framework.",
			"Dia"=>"Viernes",
			"Hora"=>"14:15 - 15:15",
			"Empresa"=>"2º DAW"),

		);

$miJSON = json_encode($actividades);
echo $miJSON;
?>